config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  resources :users
end

app/models/allergen.rb
class Allergen < ActiveRecord::Base
    belongs_to :user
    belongs_to :ingredient
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
    has_many :recipe_ingredients
    has_many :recipes, :through => :recipe_ingredients

    has_many :allergens
    has_many :users, :through => :allergens
end 

app/models/measurement_portion.rb
class MeasurementPortion < ActiveRecord::Base
    has_many :recipe_ingredients
    has_many :recipes, :through => :recipe_ingredients
end 

app/models/measurement_quantity.rb
class MeasurementQuantity < ActiveRecord::Base
    has_many :recipe_ingredients
    has_many :recipes, :through => :recipe_ingredients
end 

app/models/measurement_unit.rb
class MeasurementUnit < ActiveRecord::Base
    has_many :recipe_ingredients
    has_many :recipes, :through => :recipe_ingredients
end 

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :user
    # has_and_belongs_to_many :users

    has_many :recipe_ingredients
    has_many :ingredients, :through => :recipe_ingredients

    has_many :measurement_portions, :through => :recipe_ingredients
    has_many :measurement_units, :through => :recipe_ingredients
end 

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
    belongs_to :recipe
    belongs_to :ingredient
    belongs_to :measurement_unit
    belongs_to :measurement_portion
end 

app/models/user.rb
class User < ActiveRecord::Base
    has_many :recipes
    
    # has_and_belongs_to_many :recipes

    has_many :allergens
    has_many :ingredients, :through => :allergens
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
        @recipes = Recipe.all
    end 

    def show
        @recipe = Recipe.find(params[:id])
    end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end 

    def show
        @user = User.find(params[:id])
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergenLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Current List of Recipes</h1>

<ol>
<% @recipes.each do |recipe| %>
   <li><%= link_to recipe.name, recipe_path(recipe) %></li>
<% end %>
</ol>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Instructions:</h2>
<p><%= @recipe.description %></p>

<h2>Ingredients:</h2>
<ul>
    <% @recipe.recipe_ingredients.each do |ingredient| %>
        <li><%= "#{ingredient.measurement_portion.portions}#{ingredient.measurement_unit.desc} #{ingredient.ingredient.name}"%></li>
    <% end %>

</ul>


<%= link_to "Recipe created by #{@recipe.user.name}", user_path(@recipe.user) %>

app/views/users/index.html.erb
<h1>Current List of Users:</h1>

<ol>
    <% @users.each do |user| %>
        <li><%= link_to user.name, user_path(user) %></li>
    <% end %>
</ol>

app/views/users/show.html.erb
<h1>Profile for <%=@user.name%></h1>
<h3>Bio:</h3>
<p><%= @user.bio %></p>

<h2>List of recipes <%=@user.name%> has created: </h2>

<ol>
    <% @user.recipes.each do |recipe| %>
        <li>
            <%= link_to recipe.name, recipe_path(recipe) %>
        </li>
    <% end %>
</ol>